### ISSUE TITLE
Error importing dicom parser related to libmagic.

### ISSUE THREAD

**Issue by nicolasperezdeo** [ZviBaratz/dicom_parser#24]
I am facing the following issue when importing _dicom parser_:

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/nicolasperezdeolaguer/Documents/cataract-tools/cataract_tools/core/io.py", line 13, in <module>
    import dicom_parser
  File "/Users/nicolasperezdeolaguer/.virtualenvs/cataract-tools/lib/python3.9/site-packages/dicom_parser/__init__.py", line 8, in <module>
    from dicom_parser.series import Series
  File "/Users/nicolasperezdeolaguer/.virtualenvs/cataract-tools/lib/python3.9/site-packages/dicom_parser/series.py", line 15, in <module>
    from dicom_parser.utils.mime_generator import generate_by_mime
  File "/Users/nicolasperezdeolaguer/.virtualenvs/cataract-tools/lib/python3.9/site-packages/dicom_parser/utils/mime_generator.py", line 15, in <module>
    import magic
  File "/Users/nicolasperezdeolaguer/.virtualenvs/cataract-tools/lib/python3.9/site-packages/magic/__init__.py", line 210, in <module>
    libmagic = loader.load_lib()
  File "/Users/nicolasperezdeolaguer/.virtualenvs/cataract-tools/lib/python3.9/site-packages/magic/loader.py", line 39, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

My project requirements are the following:

`install_requirements = ['setuptools>=51.2,<57.0', 'pydicom>=2.0,<2.1',
                            'numpy>=1.16,<1.20', 'matplotlib>=3.3,<3.4', 'opencv-python>=4.4,<4.5',
                            'dicom-parser>=0.1,<1.0']`

Working on MacOS Big Sur and Python 3.9. 

I also tried to separately pip install libmagic but did not really solve the issue. Any thoughts on it? 

Thank you for your time!

**Comment by ZviBaratz** [comment]
Hi @nicolasperezdeo, [`libmagic`](https://man7.org/linux/man-pages/man3/libmagic.3.html) is a Linux library used by the [`python-magic`](https://github.com/dveselov/python-libmagic) package. It is used in only in cases where *.dcm* files are generated by mime-type rather than by extension. I'll try and create a quick patch to make this dependency optional and prevent the exception in normal usage sometime in the next couple of days. 
Thank you for reporting!

**Comment by nicolasperezdeo** [comment]
Hi @ZviBaratz , thank you for your fast reply! Okay, that makes sense. If you could do that it would be perfect. I am trying to unpack the (0029, 1010), (0029,1020) attributes of a DICOM file generated by an Oculus Pentacam device. It is different from the Siemens MRI that you describe but hopefully, your library will work for the purpose. Thank you again!
